
version: '3'
services:
  mongodb:
    image: "leafney/alpine-mongo:latest"
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=DiceDB
    ports:
      - "27017:27017"
    command: mongodb --bind_ip=0.0.0.0
  dicemanager:
    build: .
    links:
      - mongodb
    ports:
      - "5000:5000"
    volumes: # for bind volume
      - '.:/code'
    environment:
      PYTHONUNBUFFERED: 'true'